env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LANG=en_US.UTF-8

matrix:
  include:
  - os: linux
    sudo: false
    language: android
    android:
      components:
      - tools
      - platform-tools
      - build-tools
      - android
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt:
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    env: CORDOVA_VERSION="9.0.0" CORDOVA_PLATFORM="android" CORDOVA_PLATFORM_VERSION="9.0.0"

  - os: osx
    language: objective-c
    osx_image: xcode12.2
    env: CORDOVA_VERSION="9.0.0" CORDOVA_PLATFORM="ios" CORDOVA_PLATFORM_VERSION="6.2.0"

  - os: linux
    env: CORDOVA_VERSION="9.0.0" CORDOVA_PLATFORM="browser" CORDOVA_PLATFORM_VERSION="6.0.0"

before_install:
- nvm install --lts
- PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH ; export PATH
- if [[ "$CORDOVA_PLATFORM" == "android" ]]; then yes | sdkmanager "build-tools;26.0.0" "platforms;android-26" ; fi

script:
- bash ./test/test-default.sh $CORDOVA_VERSION $CORDOVA_PLATFORM $CORDOVA_PLATFORM_VERSION
- if [[ "$CORDOVA_PLATFORM" == "android" ]]; then bash ./test/test-with-3-plugins.sh $CORDOVA_VERSION $CORDOVA_PLATFORM $CORDOVA_PLATFORM_VERSION cordova-plugin-androidx-adapter cordova-android-play-services-gradle-release cordova-android-firebase-gradle-release; fi
